---
# Source: oes/charts/spinnaker/templates/deployments/create-sample-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: isd311-create-sample-app
spec:
  template:
    spec:
      serviceAccountName: isd311-spinnaker-halyard
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      restartPolicy: OnFailure
      volumes:
      - secret:
          secretName: isd311-spinnaker-spin-config
        name: spin-config
      - configMap:
          defaultMode: 420
          name: isd311-spinnaker-spin-pipeline-import
        name: spin-pipeline-import
      - name: spin-pipeline-config
        emptyDir: {}
      containers:
      - command:  
        - bash
        - /tmp/config/spin-pipeline-import.sh
        name: sample-pipeline-install
        image: quay.io/opsmxpublic/spin-sample-pipeline:1.0
        volumeMounts:         
        - name: spin-pipeline-config
          mountPath: /tmp/config/git
        - mountPath: /tmp/config
          name: spin-pipeline-import
        - mountPath: /tmp/config/spin
          name: spin-config
