---
# Source: oes/charts/spinnaker/templates/ingress/deck.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-isd311-spin
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/issue-temporary-certificate: "true"
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
  name: isd-spinnaker-deck
  labels:
    app: "isd-spinnaker"
    heritage: "Helm"
    release: "isd"
    chart: "spinnaker-2.2.3"
spec:
  rules:
  - host: "spindeck311.iswstash.opsmx.com"
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: spin-deck
            port:
              number: 9000
  tls:
  - hosts:
    - spindeck311.iswstash.opsmx.com
    secretName: spin-deck-ingress
