---
# Source: oes/charts/minio/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: isd311-minio
  labels:
    app: minio
    chart: minio-8.0.9
    release: isd311
    heritage: Helm
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: minio
      release: isd311
  template:
    metadata:
      name: isd311-minio
      labels:
        app: minio
        release: isd311
      annotations:
        checksum/secrets: 88a6d3477c7ffbfac5a30d976f7971cd38d1628ecd68385c33b1588e79f154c7
        checksum/config: 12874aa4f3d2b38d5be76ebd97963bbd0b2d9dcb17896fead756416f1705a674
    spec:
      serviceAccountName: "isd311-minio"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: minio
          image: "minio/minio:RELEASE.2020-12-03T05-49-24Z"
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/sh"
            - "-ce"
            - "/usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server /export"
          volumeMounts:
            - name: export
              mountPath: /export            
          ports:
            - name: http
              containerPort: 9000
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: isd311-minio
                  key: accesskey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: isd311-minio
                  key: secretkey
          resources:
            requests:
              memory: 4Gi      
      volumes:
        - name: export
          persistentVolumeClaim:
            claimName: isd311-minio
        - name: minio-user
          secret:
            secretName: isd311-minio
