---
# Source: oes/charts/minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: isd311-minio
  labels:
    app: minio
    chart: minio-8.0.9
    release: isd311
    heritage: Helm
type: Opaque
data:
  accesskey: "encrypted:miniopassword:miniopassword"
  secretkey: "encrypted:miniopassword:miniopassword"
