apiVersion: v1
data:
  url: github.com/yugaa22/isd311 ## e.g github.com/ksrinimba/gitops-repo, url without the leading "https://", the "git-repo" in the documentation
  username: yugaa22
  gitemail: yugaa22@gmail.com
  
  #####################################################################################################
  # Typically, there is no need to change the values below this line, please check the "nameaspace"
  #####################################################################################################
  branch: master         # Gitrepo branch, MUST be the default branch
  chartVersion: 3.11.4     # Helm Chart Version
  release: isd      # ISD helm-release version, default is oes
  currentISDVersion: "3.11"
  namespace: isd311 # Namespace to install ISD, best not to change 
  secrets: gittoken,ldappassword,dbpassword,keystorepassword,rabbitmqpassword,saporpassword,redispassword,miniopassword,ldapconfigpassword
kind: ConfigMap
metadata:
  name: upgrade-inputcm
