---
# Source: oes/charts/openldap/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: isd-openldap
  labels:
    app: openldap
    chart: openldap-1.2.3
    release: isd
    heritage: Helm
type: Opaque
data:
  LDAP_ADMIN_PASSWORD: "opsmxadmin123"
  LDAP_CONFIG_PASSWORD: "opsmxconfig123"
