---
# Source: oes/charts/openldap/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: isd311-openldap
  labels:
    app: openldap
    chart: openldap-1.2.3
    release: isd311
    heritage: Helm
type: Opaque
data:
  LDAP_ADMIN_PASSWORD: "encrypted:ldappassword:ldappassword"
  LDAP_CONFIG_PASSWORD: "encrypted:ldapconfigpassword:ldapconfigpassword"
