---
# Source: oes/charts/gitea/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: isd311-postgresql
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.3.17
    app.kubernetes.io/instance: isd311
    app.kubernetes.io/managed-by: Helm
  namespace: isd311
type: Opaque
data:
  postgresql-postgres-password: "bW9wVmV2dUpETA=="
  postgresql-password: "Z2l0ZWE="
