apiVersion: v1
stringData:
  git_secret_token: ENC(sMmzDGVV4xuN/dTiHQ1cgK+XvjDpU0xrA+M7c2n5RYyywBoR/4Qy/gIHb5pPGpu4Zoqm3auaJcc=)
  AWS_ACCESS_KEY_ID: ''
  AWS_SECRET_ACCESS_KEY: ''
  git_pr_token: ''
kind: Secret
metadata:
  name: git-token
type: Opaque
