apiVersion: v1
stringData:
  config: |
    auth:
      basic:
        password: ENC(xg2+N4h1GqX4WV2dyNJ0yEJFD90l5qcu)
        username: admin
      enabled: true
    gate:
      endpoint: http://sapor-gate:8084
kind: Secret
metadata:
  name: local-spin-cli-config
