apiVersion: v1
data:
  repo.properties: |
    #properties file for pipeline promotion scripts

    repo_type=git
    repo_name=isd311
    root_folder=

    git_url=github.com
    git_project=yugaa22
    git_user=yugaa22
kind: ConfigMap
metadata:
  name: pipe-promot-config
