apiVersion: v1
stringData:
  config: |
    auth:
      basic:
        password: ENC(dXNxblVRN9ptsgxN+5rcaMS0xwjofFb+)
        username: admin
      enabled: true
    gate:
      endpoint: http://sapor-gate:8084
kind: Secret
metadata:
  name: spin-cli-config
