---
# Source: oes/charts/spinnaker/templates/secrets/spin-config.yaml
apiVersion: v1
kind: Secret
metadata:
  name: isd311-spinnaker-spin-config
  labels:
    app: "isd311-spinnaker"
    heritage: "Helm"
    release: "isd311"
    chart: "spinnaker-2.2.3"
stringData:
  config: |
    auth:
      basic:
        password: encrypted:saporpassword:saporpassword
        username: admin
      enabled: true
    gate:
      endpoint: http://sapor-gate:8084
